title: Yazeed Alaudah
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://yalaudah.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
- title: Publications
   url: /about
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: yalaudah
   twitter: alaudah
   facebook: brianmaierjr
   email: yalaudah@gmail.com

google_analytics: "UA-74108555-1"
