title: Yazeed Alaudah
description: I'm a PhD student at Georgia Tech

url: http://www.yalaudah.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: 
  - jekyll-paginate
  - jemoji
paginate: 5


navigation:
 - title: Home
   url: /index.html
 - title: Research
   url: /research
 - title: Publications
   url: /publications
 - title: Reading
   url: /reading
 - title: About Me
   url: /aboutme

social:
   github: yalaudah
   twitter: alaudah
   linkedin: alaudah
   email: yalaudah@gmail.com

google_analytics: "UA-74108555-1"
